sudo: true
language: cpp
os:
- osx
compiler:
- gcc
cache:
  directories:
  - "$HOME/Library/Caches/Homebrew"
script:
- curl -L https://rawgit.com/InsightSoftwareConsortium/ITKPythonPackage/master/scripts/macpython-download-cache-and-build-module-wheels.sh
  -O
- chmod u+x macpython-download-cache-and-build-module-wheels.sh
- "./macpython-download-cache-and-build-module-wheels.sh"
- tar -zcvf dist.tar.gz dist/
- curl -F file="@dist.tar.gz" https://filebin.ca/upload.php

deploy:
  provider: pypi
  user: "T4mmi"
  password:
    secure: XOyH10Yx1Z2923mgNfiiU54sgUDwq/gssWVkX3fnK1nwC/exm4KO2mEhpXDdXcHZ8mjsmgATb2gVJjFCizw4gKzvcatc5EijwoznF6l2I6ISy6vXf5INKb8oI8mM0dpzUWZCFhM3Auo45FbIZluc/M0NAA12ceT4g0uyGDRzrr+6BQqQ4AD2wsyuPyadPE4AGJvUbiOqRtR36oHK6RzwjwwZ6G1KFvpC1URygFMTzIO4DFlBaAjhoTulOZMKfK7kphMKk1e1ccOQKViwuSaEKkJu4+Etn84Se2giXa+7Rxt/C+/V3auxly15rPbJby6K+LTvpT0rj/B0WGMO+HjEPsP/ApK+MP3tCzrZP5HninwHGD5xA1hh1DFGC6pyecKy8pFqysH9/D8kkaXZS8NaeMKbdZMkBeJ+fWPEIXXdznOMzn3ejHAc48MzfPhkTlHrpkgZTnarAHbn7bSINN3/8Fuyv6VvB6e2U6ioxUDo+0tr2CJG8Cn+1/xeL7SyUcrSbk7IFCHFNkRxngay0fvdjZ1C2OvvJ+CVH4uljz101ATZHY92Y0Dx1a8qN5UX6MlWLqHZOeeIxn6c33QfzTRgi8Urn8JN1XDznsHxQPnfYci+2vE3mO1Ni3uniVGbd7VPbgFUNuq1KTE0uBzQm0HNwFueDwphIrQ9qyHndM4GPH4=
  on:
    branch: master
    tags: true